### ISSUE TITLE
services: add new high-level api for reading many records at once

### ISSUE THREAD

**Issue by lnielsen** [inveniosoftware/invenio-records-resources#189]
For Vocabularies, we have two use cases:

- Retrieve a lower number of records (~10) that are being displayed in facets (e.g. 10 language records)
  - For instance language vocabulary has 1000+ records so unfeasible to fetch all.
- Retrieve all records for a given type (<100) and potentially cache the result under a provided key
  - For instance, resource type has ~20 records, and all can be cached so when facets are displayed we just retrieve from the cache.

The goal here is that the methods are very performant as they will happen during search.

**Read many**

The API of read many *could* (but doesn't have to) look like this:

```
service.read_many(identity, ids=['', ...])
```

It could use the [search engine multi get](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-multi-get.html). For that we require uuids to be provided, so either a query must be made to PIDStore to retrieve all uuids. Alternatively we get everthing from the DB.

**Read all**

Perhaps the ``scan()`` method can be extended with cache capabilities or a ``read_all()`` method simply uses the same as ``read_many()`` just retrieving everything.

```
service.scan(identity, params={}, cache_key='vocabs.resource_types')
```

E.g. in vocabularies, we would need to query by the type for generic vocabularies.

**Comment by ppanero** [comment]
## From IRL talks:

**Invenio-Records-Resources**

- It should *not* return the vocabulary records, but just the key-label pairs. This is desired to reduce data transferences, in addition using directly the ES DSL will allow to make simpler queries and reduce the overhead of `_search` (aggregation calculations, etc.)

`read_many`:
- No caching. It makes not much sense since the number of keys will vary very often.

`read_all`:
- Caching for smaller sets, or even bigger... Where do we put the threshold? Caching all for now.
- Might need a longer key (e.g. due to languages, etc.)


**Invenio-RDM-Records**
- The UI serializer will give a set of *keys* and *labels*.

**Invenio-APP-RDM**
- Jinja will try to get the vocabularies from cache.
- If it's a miss, they will be queried at serializer/service level (?)

**Comment by ppanero** [comment]
requires https://github.com/inveniosoftware/invenio-records/pull/254

**Comment by lnielsen** [comment]
Pending #243
